repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8  # Use the latest stable version or pin as needed
    hooks:
      - id: ruff
        args: ["--fix"]  # Auto-fix issues where possible
