# This workflow will run tox for Python projects
name: Tox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y uv
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      - name: Run tox
        run: tox
